# apt update & upgrade
# パッケージインストール

- name: apt update & upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: パッケージインストール
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - emacs-nox
    - language-pack-ja
    - apache2
    - curl
    - python3-pip
    - certbot
    - python3-certbot-apache
    - composer
  notify: restart apache

- name: Apacheモジュール
  become: true
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - 'authz_groupfile'
    - 'rewrite'
    - 'ssl'
    - 'userdir'
  notify: restart apache

- name: powerline-shell
  become: yes
  become_user: ken
  pip:
    name: powerline-shell
