# POPFileインストール
# dbを解凍したら起動

- name: popfileインストール
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - popfile
    - libtext-kakasi-perl
    - sqlite
    - libdbd-sqlite2-perl

- name: popfile停止
  become: true
  service: name=popfile state=stopped
