- name: PHPインストール (MySQLインストールの後)
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - php7.4
    - php7.4-cli
    - php7.4-cgi
    - php7.4-curl
    - php7.4-intl
    - php7.4-mysql
    - libapache2-mod-php7.4
    - phpmyadmin
  notify:
    - restart apache
    - restart mysql

- name: phpMyAdminリンク (1)
  become: true
  file:
    src: /etc/phpmyadmin/apache.conf
    dest: /etc/apache2/conf-available/phpmyadmin.conf
    state: link
  notify:
    - restart apache
    - restart mysql

- name: phpMyAdminリンク (2)
  become: true
  file:
    src: /etc/apache2/conf-available/phpmyadmin.conf
    dest: /etc/apache2/conf-enabled/phpmyadmin.conf
    state: link
  notify:
    - restart apache
    - restart mysql
