- name: MySQLデータベース削除
  become: true
  mysql_db:
    state: absent
    name: "{{ item }}"
  with_items:
    - 100
    - bookmark
    - dizmail
    - dizmail6
    - find_similar_filename
    - kabu
    - moodle
    - mt1
    - suyama
    - terminalroad_dev2
    - terminalroad_production
    - tournament
    - tv
    - zanshin
  notify: restart mysql

- name: MySQLインポート
  become: true
  mysql_db:
    state: import
    name: "{{ item.db }}"
    target: "/home/ken/ansible_tmp/{{ item.src }}.dump.sql.gz"
  with_items:
    - { db: '100', dest: '100' }
    - { db: 'bookmark', dest: 'bookmark' }
    - { db: 'dizmail', dest: 'dizmail' }
    - { db: 'dizmail6', dest: 'dizmail6' }
    - { db: 'find_similar_filename', dest: 'find_similar_filename' }
    - { db: 'kabu', dest: 'kabu' }
    - { db: 'moodle', dest: 'moodle' }
    - { db: 'mt1', dest: 'mt1' }
    - { db: 'suyama', dest: 'suyama' }
    - { db: 'terminalroad_dev2', dest: 'terminalroad_dev2' }
    - { db: 'terminalroad_production', dest: 'terminalroad_production' }
    - { db: 'tournament', dest: 'tournament' }
    - { db: 'tv', dest: 'tv' }
    - { db: 'zanshin', dest: 'zanshin' }
  notify: restart mysql

- name: MySQLユーザ作成 (ops)
  become: true
  mysql_user:
    name: ops
    password: "{{ mysql_ops_pass }}"
    state: present
    priv: "*.*:ALL"
    host: localhost
  notify: restart mysql

- name: MySQLユーザ作成 (app)
  become: true
  mysql_user:
    name: app
    password: "{{ mysql_app_pass }}"
    state: present
    priv: "*.*:ALTER,CREATE,CREATE TEMPORARY TABLES,CREATE VIEW,DELETE,DROP,EXECUTE,FILE,INDEX,INSERT,LOCK TABLES,SELECT,UPDATE"
    host: localhost
  notify: restart mysql
