- name: MySQLデータベース削除
  become: true
  mysql_db:
    state: absent
    name: "{{ item }}"
  with_items:
    - 100
    - bookmark
    - dizmail
    - dizmail6
    - moodle
    - tournament
    - tv_reminder
    - zanshin
  notify: restart mysql

- name: MySQLインポート
  become: true
  mysql_db:
    state: import
    name: "{{ item.db }}"
    target: "/home/ken/ansible_tmp/{{ item.src }}.dump.sql.gz"
  with_items:
    - { db: '100', src: '100' }
    - { db: 'bookmark', src: 'bookmark' }
    - { db: 'dizmail', src: 'dizmail' }
    - { db: 'dizmail6', src: 'dizmail6' }
    - { db: 'moodle', src: 'moodle' }
    - { db: 'tournament', src: 'tournament' }
    - { db: 'tv_reminder', src: 'tv_reminder' }
    - { db: 'zanshin', src: 'zanshin' }
  notify: restart mysql

- name: MySQLユーザ作成 (ops)
  become: true
  mysql_user:
    name: ops
    password: "{{ mysql_ops_pass }}"
    state: present
    priv: "*.*:ALL"
    host: localhost
  notify: restart mysql

- name: MySQLユーザ作成 (app)
  become: true
  mysql_user:
    name: app
    password: "{{ mysql_app_pass }}"
    state: present
    priv: "*.*:ALTER,CREATE,CREATE TEMPORARY TABLES,CREATE VIEW,DELETE,DROP,EXECUTE,FILE,INDEX,INSERT,LOCK TABLES,SELECT,UPDATE"
    host: localhost
  notify: restart mysql
