- name: MySQLユーザ作成 (ops)
  become: true
  mysql_user:
    name: ops
    password: "{{ mysql_ops_pass }}"
    state: present
    priv: "*.*:ALL"
    host: localhost
  notify: restart mysql

- name: MySQLユーザ作成 (app)
  become: true
  mysql_user:
    name: app
    password: "{{ mysql_app_pass }}"
    state: present
    priv: "*.*:ALTER,CREATE,CREATE TEMPORARY TABLES,CREATE VIEW,DELETE,DROP,EXECUTE,FILE,INDEX,INSERT,LOCK TABLES,SELECT,UPDATE"
    host: localhost
  notify: restart mysql

- name: MySQLデータベース削除
  become: true
  mysql_db:
    state: absent
    name: "{{ item }}"
  with_items:
    - bookmark
    - tv
  notify: restart mysql

- name: MySQLインポート
  become: true
  mysql_db:
    state: import
    name: "{{ item.db }}"
    target: "/home/ken/ansible_tmp/{{ item.dest }}.dump.sql.gz"
  with_items:
    - { db: 'bookmark', dest: 'bookmark' }
    - { db: 'tv', dest: 'tv' }
  notify: restart mysql
