- name: MySQL：ダンプ
  mysql_db:
    state: dump
    login_user: ops
    login_password: "{{ vault_mysql_pass }}"
    name: "{{ item.db }}"
    target: "/home/ken/ansible_tmp/{{ item.dest }}.dump.sql.gz"
  with_items:
    - { db: 'bookmark', dest: 'bookmark' }
    - { db: 'tv', dest: 'tv' }
