- name: MySQL：ダンプ
  mysql_db:
    state: dump
    login_user: ops
    login_password: "{{ vault_mysql_pass }}"
    name: "{{ item.db }}"
    target: "/home/ken/ansible_tmp/{{ item.dest }}.dump.sql.gz"
  with_items:
    - { db: '100', dest: '100' }
    - { db: 'bookmark', dest: 'bookmark' }
    - { db: 'dizmail', dest: 'dizmail' }
    - { db: 'dizmail6', dest: 'dizmail6' }
    - { db: 'find_similar_filename', dest: 'find_similar_filename' }
    - { db: 'kabu', dest: 'kabu' }
    - { db: 'moodle', dest: 'moodle' }
    - { db: 'mt1', dest: 'mt1' }
    - { db: 'suyama', dest: 'suyama' }
    - { db: 'terminalroad_dev2', dest: 'terminalroad_dev2' }
    - { db: 'terminalroad_production', dest: 'terminalroad_production' }
    - { db: 'tournament', dest: 'tournament' }
    - { db: 'tv', dest: 'tv' }
    - { db: 'zanshin', dest: 'zanshin' }
