# mysqlインストール

- name: MySQLインストール
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
  notify:
    - restart mysql

- name: Python3ライブラリインストール
  become: true
  ansible.builtin.pip:
    name: mysqlclient

- name: MySQL初期設定
  become: true
  ansible.builtin.shell: mysql_secure_installation --use-default --password=setup
  register: result
  changed_when: "'VALIDATE PASSWORD PLUGIN' in result.stdout"
  notify: restart mysql
