# ユーザ作成 + 公開鍵登録

- name: ユーザ作成
  become: true
  ansible.builtin.user:
    name: "{{ user_name }}"
    createhome: yes
    # mkpasswd --method=SHA-512
    password: "{{ user_pass | password_hash('sha512') }}"
    shell: /bin/bash
    group: staff
    groups: adm, cdrom, sudo, dip, plugdev, lxd
    state: present

- name: 公開鍵登録
  become: true
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '/home/{{ user_name }}/.ssh/authorized_keys') }}"

- name: ユーザディレクトリを 0755に
  become: true
  ansible.builtin.file:
    path: "/home/{{ user_name }}"
    mode: '0755'
