# .emacs.d git clone

- name: リンク .gitconfig (.emacs.d)
  become: true
  ansible.builtin.file:
    src: "/home/{{ user_name }}/.emacs.d/.gitconfig_ken197x"
    dest: "/home/{{ user_name }}/.gitconfig"
    owner: "{{ user_name }}"
    group: staff
    state: link

- name: リンク .gitignore (.emacs.d)
  become: true
  ansible.builtin.file:
    src: "/home/{{ user_name }}/.emacs.d/.gitignore_global"
    dest: /home/{{ user_name }}/.gitignore
    owner: "{{ user_name }}"
    group: staff
    state: link

- name: リンク .gitignore (.emacs.d)
  become: true
  ansible.builtin.file:
    src: "/home/{{ user_name }}/.emacs.d/ssh_config_ken197x"
    dest: "/home/{{ user_name }}/.ssh/config"
    owner: "{{ user_name }}"
    group: staff
    state: link

- name: テンプレート .tmux.conf (.emacs.d)
  become: true
  ansible.builtin.template:
    src: tmux.j2
    dest: "/home/{{ user_name }}/.tmux.conf"
    owner: "{{ user_name }}"
    group: staff
    mode: 0644

- name: chown .gitconfig
  become: true
  ansible.builtin.shell: "chown -h {{ user_name }}.staff /home/{{ user_name }}/.gitconfig"

- name: chown .gitignore
  become: true
  ansible.builtin.shell: "chown -h {{ user_name }}.staff /home/{{ user_name }}/.gitignore"

- name: chown .ssh/config
  become: true
  ansible.builtin.shell: "chown -h {{ user_name }}.staff /home/{{ user_name }}/.ssh/config"
