- name: テンポラリディレクトリ作成 (ansible)
  become: true
  file:
    path: /home/ken/ansible
    owner: ken
    group: staff
    state: directory

- name: テンポラリディレクトリ削除 (tmp) ※ 古いのを削除するため
  become: true
  file:
    path: /home/ken/ansible/tmp
    owner: ken
    group: staff
    state: absent

- name: テンポラリディレクトリ作成 (tmp)
  become: true
  file:
    path: /home/ken/ansible/tmp
    owner: ken
    group: staff
    state: directory

- name: アーカイブしたファイル(ディレクトリ)をコピー (ローカル → リモート)
  become: true
  copy:
    src: "/home/ken/ansible/tmp"
    dest: "/home/ken/ansible"
    owner: ken
    group: staff

- name: (解凍上書き前に) 転送先のディレクトリを削除
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/home/ken/moodle_data'
    - '/home/ken/data'
    - '/home/ken/repositories'
    # - '/home/ken/public_html'
    - '/var/public_smb'
    - '/var/www/html'
    - '/etc/popfile'
    - '/var/lib/popfile'

- name: アーカイブを解凍 (アーカイブ時にパス指定がルートからなのでルートで解凍)
  become: true
  command: tar xzvf "/home/ken/ansible/tmp/{{ item }}" -C /
  with_items:
    - 'moodle_data.tgz'
    - 'data.tgz'
    - 'repositories.tgz'
    # - 'public_html.tgz'
    - 'public_smb.tgz'
    - 'html.tgz'
    - 'popfile_etc.tgz'
    - 'popfile_lib.tgz'
