- name: テンポラリディレクトリ作成 (ansible)
  become: true
  file:
    path: /home/ken/ansible
    owner: ken
    group: staff
    state: directory

- name: テンポラリディレクトリ削除 (tmp) ※ 古いのを削除するため
  become: true
  file:
    path: /home/ken/ansible_tmp
    owner: ken
    group: staff
    state: absent

- name: テンポラリディレクトリ作成 (tmp)
  become: true
  file:
    path: /home/ken/ansible_tmp
    owner: ken
    group: staff
    state: directory

- name: アーカイブしたファイル(ディレクトリ)をコピー (ローカル → リモート)
  become: true
  copy:
    src: "/home/ken/ansible_tmp"
    dest: "/home/ken/ansible"
    owner: ken
    group: staff

- name: (解凍上書き前に) 転送先のディレクトリを削除
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/home/ken/ansible'
    - '/home/ken/moodle_data'
    - '/home/ken/data'
    - '/home/ken/repositories'
    - '/home/ken/public_html'
    - '/var/public_smb'
    - '/var/www/html'
    - '/etc/popfile'
    - '/var/lib/popfile'

- name: アーカイブを解凍 (アーカイブ時にパス指定がルートからなのでルートで解凍)
  become: true
  command: tar xzvf "/home/ken/ansible_tmp/{{ item }}" -C /
  with_items:
    - 'ansible.tgz'
    - 'moodle_data.tgz'
    - 'data.tgz'
    - 'repositories.tgz'
    - 'public_html.tgz'
    - 'public_smb.tgz'
    - 'html.tgz'
    - 'popfile_etc.tgz'
    - 'popfile_lib.tgz'

- name: 単発コピー mydns.jp
  become: true
  copy:
    src: "/home/ken/mydns.sh"
    dest: "/home/ken/mydns.sh"
    owner: ken
    group: staff
    mode: 0755

- name: 単発コピー shell
  become: true
  copy:
    src: "/home/ken/{{ item.src }}"
    dest: "/home/ken/{{ item.dest }}"
    owner: ken
    group: staff
    mode: 0644
    backup: yes
  with_items:
    - { src: '.bash_logout', dest: '.bash_logout' }
    - { src: '.bashrc', dest: '.bashrc' }
    - { src: '.htpasswd', dest: '.htpasswd' }
    - { src: '.profile', dest: '.profile' }
