# POPFile

- name: popfile停止
  become: true
  ansible.builtin.service: name=popfile state=stopped

- name: (解凍上書き前に) 転送先のディレクトリを削除
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/var/lib/popfile'

- name: アーカイブを解凍 (アーカイブ時にパス指定がルートからなのでルートで解凍)
  become: true
  ansible.builtin.command: tar -xzf "/home/{{ user_name }}/ansible_tmp/{{ item }}" -C /
  with_items:
    - 'var_popfile.tgz' # popfile は移管が終わった後

- name: popfile再起動
  become: true
  ansible.builtin.service: name=popfile state=started
