- name: restart apache
  become: true
  ansible.builtin.service: name=apache2 state=restarted

- name: restart mysql
  become: true
  ansible.builtin.service: name=mysql state=restarted

- name: restart samba
  become: true
  ansible.builtin.service: name={{ item }} state=restarted
  with_items:
    - smbd
    - nmbd
